### ISSUE TITLE
Host dataset on HF

### ISSUE THREAD

**Issue by NielsRogge** [sled-group/3D-GRAND#1]
Hi,

Niels here from the open-source team at Hugging Face. Congrats on your work! I discovered your work through the paper page: https://huggingface.co/papers/2406.05132.

It's great to see the 🤗 Space available using Gradio.

Would you be interested in providing the dataset on the hub as well? So that people can do:

```python
from datasets import load_dataset

dataset = load_dataset("sled-group/3d-grand")
```

We do support "gated access" which allows you to manually review anyone who wants to get access to the dataset (similar to how models like LLaMa are gated): https://huggingface.co/docs/hub/en/datasets-gated.

Let us know if you need any help.

Cheers,

Niels
ML Engineer @ HF 🤗

**Comment by jedyang97** [comment]
Hi @NielsRogge , yes we actually are in the process of migrating to HF datasets. Just need to finalize a few things before we make it public. Thanks for checking in though - HF datasets is indeed a better solution.

**Comment by jedyang97** [comment]
Hi @NielsRogge,

Just want to let you know we have migrated to HF Datasets at: https://huggingface.co/datasets/sled-umich/3D-GRAND. thanks!

**Comment by NielsRogge** [comment]
Thanks a lot! Would be great to link it in this README if possible :)

Also, I saw the checkpoints are present inside the Space: https://huggingface.co/spaces/jedyang97/3D-GRAND/tree/main/checkpoints, would be great to host them in separate model repos
