### ISSUE TITLE
Dropbox download

### ISSUE THREAD

**Issue by yruns** [sled-group/3D-GRAND#2]
Your work is very valuable!

Additionally, could you provide a download method other than Dropbox? Or could you offer a way to batch download from Dropbox? When I tried to download 3D-GRAND directly, I was notified that the file is too large to download.

**Comment by jedyang97** [comment]
Hi @yruns ,

Very timely question! We just migrated the dataset to Huggingface: https://huggingface.co/datasets/sled-umich/3D-GRAND to enable a better user experience.

We are in the process of finalizing the upload for a few big text files. but please follow the HF page for latest update. Thanks for your interest in our dataset!

**Comment by yruns** [comment]
Thanks for your reply~
